spark.app.name=MySparkApplication

spark.sql.shuffle.partitions=20
spark.local.dir=D:/spark-tmp

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=spark-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

postgres.url=jdbc:postgresql://localhost:5431/sparkdb
postgres.user=postgres
postgres.password=postgres
postgres.table=kafka_messages